---
title: "ic_amamentação"
output: 
  html_document:
date: "2023-10-19"
---
  mudeiiiii
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = F, message = F)
```

## CARREGAMENTO DAS BIBLIOTECAS

```{r, warning=F, message=F}
library(tidyverse)    ### coleção de pacotes
library(janitor)      ### manipular variaveis
library(haven)        ### ler o pacote .sav    
library(labelled)     ### obter o dicionário das variaveis  
library(ggplot2)      ### construção de gráficos 
library(survival)     ### análise de sobrevivência
library(corrr)        ### talvez
library(ggfortify)    ### talvez
library(summarytools) ### talvez
library(knitr)        ### aparência de tabelas
library(kableExtra)   ### aparência de tabelas
library(git4r)
```
# Análise descritiva

## Carregamentoe limpeza da base, e criação do dicionário

```{r}
## importação da base de dados+clean_names()
dados_2 <- read_sav("dados-amamentacao.sav") %>% clean_names()
### gerando dicionário
dicionario <- dados_2 %>% 
  janitor::clean_names()%>% 
  labelled::generate_dictionary()
## vetores com nomes das variaveis de cada tipo
### variaveis de identificação
var_id <- c("n_rand", "grupo", "indic_gemelar", "indic_mae", "indic_info_ganho_peso", "indic_t", "indic_tempo","filter")
###variaveis de sim ou não string
var_sn <- c(
  "trabalha_sn", "mora_com_compan", "af_ca_mama", "orien_amam_prev",
  "gravid_plan", "gravid_desej", "complic_relac_parto",
  "uti", "amament_prev_sn",
  "t1_retorno_ao_trabalho", "t2_retorno_trabalho", "t3_retorno_trabalho"
)
###variaveis de sim ou não numeric
var_sn_10 <- c(
  "religiao_sn", "para_sn",
  "horas_trab_menor_igual7", "horas_trab_menor_7",
  "idade_menor26", "idade_menor_igual26",
  "dias_int_mae_pos_parto_menor_igual3", "dias_int_mae_pos_parto_menor3",
  "ig_parto_36", "ig_parto_37", "ajuda_para_cuidar",
  "dificuldade_para_amamentar", "dor_amamentar",
  "media_amament_prev_12", "peso_nasc_2300",
  "total_t_int_menor11", "ganho_peso_por_dia_menor_igual21",
  "t1_amamen_exclusiva_sn", "t2_amamen_exclusiva_sn", "t3_amamen_exclusiva_sn", "amamen_exclusiva_sn",
  "censura", "retorno_trabalho"
)
###variaveis de fator numeric
var_fct_num <- c(
  "ig_inclus_corrigida_35",
  "religiao_catolica_sn",
  "salario_familiar_cat", "salario_familiar_2cat",
  "idade_faixa_et"
)
###variaveis de fator cahracter
var_fct_chr <- c(
  "mamilos", "tipo_parto", "escolaridade_cat", "sexo"
)
###variaveis numéricas
var_num <- c(
  "ig_inclus_corrigida", "horas_trab_dia", "salario_familiar", "idade",
  "dias_int_mae_pos_parto", "ig_parto", "num_filhos_amamentou_todos","media_amament_prev_meses_todos",
  "peso_nasc", "uti_t_int_todos", "total_t_int", "ganho_peso_por_dia", "tempo"
)
### variaveis de fatores representados por números
var_fct <- c(var_fct_num,var_sn_10)
### arrumando a classe dos fatores
dados_2[,var_fct] <- lapply(dados_2[,var_fct], as_factor)
###limpando a base, removendo os dois valores perdidos durante acompanhamento
df_geral <- dados_2
df_geral <- df_geral %>% 
  janitor::clean_names() %>%
  dplyr::filter(!is.na(tempo_vida_ate_parada_amament_ate180)==TRUE) %>% 
  dplyr::filter(!is.na(censura)==TRUE) %>% 
  dplyr::rename(tempo=tempo_vida_ate_parada_amament_ate180)
```

## descritiva_mae

### vetor com nomes dos dados que voltados a mãe

```{r}
vet_nao_mae <- c("n_rand", "grupo", "indic_gemelar", "indic_info_ganho_peso", "indic_t", "indic_tempo","filter","sexo","peso_nasc","peso_nasc_2300","uti","uti_t_int_todos","total_t_int", "total_t_int_menor11","ganho_peso_por_dia","ganho_peso_por_dia_menor_igual21")
vet_mae <- setdiff(names(df_geral), vet_nao_mae)
## duvidas: "uti" é dos filhos, mas necessáriamente se um gêmeo foi internado, o outro também será? COLOQUEI NO VETOR PARA TIRAR
#mesma duvida para variaveis "uti_t_int_todos" , "total_t_int", "total_t_int_menor11", 
```

### dados numéricos
  
```{r}
df_mae_num <- df_geral %>% 
  dplyr::filter(indic_mae==1) %>% 
  #dplyr::select(setdiff(var_fct_num, vet_nao_mae))
  dplyr::select(var_num)
med_var_mae <- data.frame(media=colMeans(df_mae_num, na.rm = TRUE), variancia=apply(df_mae_num, 2, var, na.rm = TRUE))
med_var_mae %>% kbl() %>%kable_styling()
```

### dados de fatores

```{r results='asis'}
df_mae_fator <- df_geral %>% 
  dplyr::filter(indic_mae==1) %>% 
  dplyr::select(c(intersect(vet_mae,var_fct)))
a <- list()
for (i in names(df_mae_fator)){
  nome_2 <- "frequencia da variavel"
  nome_2 <- paste(nome_2, i)
  b <- df_mae_fator[[i]]
  a[[i]] <- as.data.frame(table(b)) %>% kable(caption=nome_2) %>% kable_styling()
  print(a[[i]])
}
```


